var __HCHUNKS=__HCHUNKS||[];
__HCHUNKS[0] = [
  "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"UTF-8\">\n<meta name=\"viewport\" content=\"width=device-width, initia",
  "l-scale=1.0\">\n<title>All Can Create. All Can Design.</title>\n<style>\n  @import url('https://fonts.googleapis.com/css2?fa",
  "mily=Inter:wght@300;400;500;600;700&family=Playfair+Display:ital,wght@0,500;1,500&display=swap');\n\n  * { margin: 0; padd",
  "ing: 0; box-sizing: border-box; }\n\n  body {\n    font-family: 'Inter', sans-serif;\n    background: #0B1120;\n    color: #E",
  "8ECF1;\n    min-height: 100vh;\n    overflow-x: hidden;\n  }\n\n  /* ==============================\n     HERO + DENSE MONTAGE",
  "\n     ============================== */\n  .hero {\n    position: relative;\n    overflow: hidden;\n  }\n  .montage {\n    dis",
  "play: grid;\n    grid-template-columns: repeat(auto-fill, minmax(105px, 1fr));\n    grid-auto-rows: 68px;\n    gap: 2px;\n  ",
  "}\n  .montage-cell {\n    overflow: hidden;\n  }\n  .montage-cell img {\n    width: 100%;\n    height: 100%;\n    object-fit: c",
  "over;\n    opacity: 0.35;\n    filter: saturate(0.5) brightness(0.7);\n    transition: opacity 0.5s, filter 0.5s;\n  }\n  .mo",
  "ntage-cell:hover img {\n    opacity: 0.7;\n    filter: saturate(0.9) brightness(1);\n  }\n  .hero-overlay {\n    position: ab",
  "solute;\n    inset: 0;\n    display: flex;\n    flex-direction: column;\n    align-items: center;\n    justify-content: cente",
  "r;\n    text-align: center;\n    background: radial-gradient(ellipse at center, rgba(11,17,32,0.5) 0%, rgba(11,17,32,0.82)",
  " 70%);\n    z-index: 2;\n    padding: 24px;\n  }\n  .hero-overlay h1 {\n    font-family: 'Playfair Display', serif;\n    font-",
  "size: 2.2rem;\n    font-weight: 500;\n    color: #F5A623;\n    letter-spacing: 0.5px;\n    margin-bottom: 8px;\n  }\n  .hero-o",
  "verlay p {\n    font-size: 0.85rem;\n    color: rgba(232,236,241,0.5);\n    font-weight: 300;\n    letter-spacing: 2px;\n  }\n",
  "  .hero-fade {\n    position: absolute;\n    bottom: 0; left: 0; right: 0;\n    height: 60px;\n    background: linear-gradie",
  "nt(to bottom, transparent, #0B1120);\n    z-index: 3;\n  }\n\n  /* ==============================\n     CONSTELLATION\n     ==",
  "============================ */\n  .constellation-wrap {\n    position: relative;\n  }\n  #constellation {\n    display: bloc",
  "k;\n    width: 100%;\n    cursor: default;\n  }\n  .pause-btn {\n    width: 28px; height: 28px;\n    border-radius: 50%;\n    b",
  "order: 1px solid rgba(255,255,255,0.12);\n    background: rgba(255,255,255,0.05);\n    color: rgba(232,236,241,0.4);\n    f",
  "ont-size: 12px;\n    cursor: pointer;\n    display: flex; align-items: center; justify-content: center;\n    transition: al",
  "l 0.25s;\n    margin: 0 auto 6px;\n  }\n  .pause-btn:hover {\n    background: rgba(255,255,255,0.12);\n    color: #E8ECF1;\n  ",
  "  border-color: rgba(255,255,255,0.3);\n  }\n\n  /* ==============================\n     INFO BAR (between constellation & g",
  "rid)\n     ============================== */\n  .info-bar {\n    max-width: 1300px;\n    margin: 0 auto;\n    padding: 10px 2",
  "4px 14px;\n    text-align: center;\n  }\n  .info-bar .ib-instruction {\n    font-size: 0.72rem;\n    color: rgba(232,236,241,",
  "0.2);\n    font-style: italic;\n    margin-bottom: 0;\n    transition: color 0.3s;\n  }\n  .info-bar.active .ib-instruction {",
  "\n    color: rgba(232,236,241,0.3);\n    margin-bottom: 8px;\n  }\n  .info-bar .ib-details {\n    display: none;\n  }\n  .info-",
  "bar.active .ib-details {\n    display: block;\n  }\n  .ib-top-line {\n    display: flex;\n    align-items: center;\n    justif",
  "y-content: center;\n    gap: 10px;\n    margin-bottom: 4px;\n  }\n  .ib-cluster { font-size: 0.62rem; font-weight: 600; lett",
  "er-spacing: 1.2px; t",
].join("");
